export const dataList = [
  { id: 1, list: "How to code clean?" },
  { id: 2, list: "Set up morning routine" },
  { id: 3, list: "Fix a bug in the code" },
  { id: 4, list: "Write unit tests" },
  { id: 5, list: "Practice coding for 30 minutes" },
  { id: 6, list: "Organize workspace" },
  { id: 7, list: "Refactor existing code" },
  { id: 8, list: "Work on personal project" },
  { id: 9, list: "Take a 5-minute break" },
  { id: 10, list: "Cook a healthy meal" },
  { id: 11, list: "Read documentation for new tools" },
  { id: 12, list: "Exercise for 30 minutes" },
  { id: 13, list: "Write clean comments in code" },
  { id: 14, list: "Plan the day ahead" },
  { id: 15, list: "Learn a new programming language" },
  { id: 16, list: "Listen to a podcast" },
  { id: 17, list: "Attend a team meeting" },
  { id: 18, list: "Update project dependencies" },
  { id: 19, list: "Review pull requests" },
  { id: 20, list: "Read a book" },
  { id: 21, list: "Prepare breakfast" },
  { id: 22, list: "Go for a walk" },
  { id: 23, list: "Debug application" },
  { id: 24, list: "Do a code review for a colleague" },
  { id: 25, list: "Take notes for a meeting" },
  { id: 26, list: "Take an online course" },
  { id: 27, list: "Clean your desk" },
  { id: 28, list: "Meditate for 10 minutes" },
  { id: 29, list: "Update your resume" },
  { id: 30, list: "Plan a weekend trip" },
  { id: 31, list: "Create a new project in GitHub" },
  { id: 32, list: "Check emails and respond" },
  { id: 33, list: "Organize calendar for the week" },
  { id: 34, list: "Write blog post on programming" },
  { id: 35, list: "Work on side hustle project" },
  { id: 36, list: "Study algorithms" },
  { id: 37, list: "Prepare lunch" },
  { id: 38, list: "Call a friend or family member" },
  { id: 39, list: "Do a quick workout" },
  { id: 40, list: "Go grocery shopping" },
  { id: 41, list: "Reflect on personal goals" },
  { id: 42, list: "Check weather forecast" },
  { id: 43, list: "Declutter workspace" },
  { id: 44, list: "Review finances" },
  { id: 45, list: "Set new weekly goals" },
  { id: 46, list: "Listen to an audiobook" },
  { id: 47, list: "Schedule doctor's appointment" },
  { id: 48, list: "Go to the gym" },
  { id: 49, list: "Tidy up your living space" },
  { id: 50, list: "Write in a journal" },
  { id: 51, list: "Cook dinner" },
  { id: 52, list: "Check social media" },
  { id: 53, list: "Watch an educational video" },
  { id: 54, list: "Plan next week's tasks" },
  { id: 55, list: "Clean the bathroom" },
  { id: 56, list: "Attend a virtual meetup" },
  { id: 57, list: "Brainstorm new project ideas" },
  { id: 58, list: "Prepare for a presentation" },
  { id: 59, list: "Relax and unwind" },
  { id: 60, list: "Review your personal development plan" },
  { id: 61, list: "Check up on your health" },
  { id: 62, list: "Unsubscribe from unwanted emails" },
  { id: 63, list: "Update LinkedIn profile" },
  { id: 64, list: "Read a programming article" },
  { id: 65, list: "Try a new recipe" },
  { id: 66, list: "Create a budget plan" },
  { id: 67, list: "Attend an online coding challenge" },
  { id: 68, list: "Relax with a hobby" },
  { id: 69, list: "Schedule time for learning" },
  { id: 70, list: "Write a thank-you note" },
  { id: 71, list: "Join an online community" },
  { id: 72, list: "Learn Git and version control" },
  { id: 73, list: "Start a new workout routine" },
  { id: 74, list: "Meditate before bed" },
  { id: 75, list: "Make your bed in the morning" },
  { id: 76, list: "Visit a local park" },
  { id: 77, list: "Test your code" },
  { id: 78, list: "Upgrade your device's software" },
  { id: 79, list: "Set a budget for the month" },
  { id: 80, list: "Work on improving your soft skills" },
  { id: 81, list: "Organize your computer files" },
  { id: 82, list: "Take a nap" },
  { id: 83, list: "Set up a personal website" },
  { id: 84, list: "Attend a coding webinar" },
  { id: 85, list: "Clean your car" },
  { id: 86, list: "Research new technologies" },
  { id: 87, list: "Take a break from screens" },
  { id: 88, list: "Check progress on long-term goals" },
  { id: 89, list: "Try a new programming framework" },
  { id: 90, list: "Enjoy a hobby outside of tech" },
  { id: 91, list: "Spend time with pets" },
  { id: 92, list: "Plan your meals for the week" },
  { id: 93, list: "Reflect on achievements for the week" },
  { id: 94, list: "Pick up a new skill" },
  { id: 95, list: "Complete a coding challenge" },
  { id: 96, list: "Learn about machine learning" },
  { id: 97, list: "Set up automated backups for files" },
  { id: 98, list: "Complete your morning skincare routine" },
  { id: 99, list: "Check in on a friend's well-being" },
  { id: 100, list: "Review current programming project" },
  { id: 101, list: "Create a schedule for the day" },
  { id: 102, list: "Explore new podcast recommendations" },
  { id: 103, list: "Read up on new coding trends" },
  { id: 104, list: "Implement new design patterns" },
  { id: 105, list: "Visit a museum or cultural place" },
  { id: 106, list: "Take an online quiz" },
  { id: 107, list: "Practice a new programming concept" },
  { id: 108, list: "Prepare a presentation for work" },
  { id: 109, list: "Try out a new productivity tool" },
  { id: 110, list: "Write a to-do list for the week" },
  { id: 111, list: "Tidy up your digital life" },
  { id: 112, list: "Plan for upcoming vacations" },
  { id: 113, list: "Test your application on different devices" },
  { id: 114, list: "Clean up your social media accounts" },
  { id: 115, list: "Reflect on your programming progress" },
  { id: 116, list: "Go for a jog" },
  { id: 117, list: "Spend time with family" },
  { id: 118, list: "Complete your work tasks for the day" },
  { id: 119, list: "Find new ways to stay productive" },
  { id: 120, list: "Plan your personal projects for the next month" },
];
